### ISSUE TITLE
BYOL-A  Is this independent of language?

### ISSUE THREAD

**Issue by parthplc** [nttcslab/byol-a#1]
Can we create vector representation using a pretrained model only for English or is it language Independent?

**Comment by daisukelab** [comment]
Hi, my quick answer is language independent. But let me clarify some more.
This research is for _general purpose audio_ representation, not for _speech recognition_.
So our encoder network is trained _without putting an assumption of the type of the sound_.
I hope this answers your question.

**Comment by daisukelab** [comment]
Hi, I guess the question might be fulfilled, so let me close for now. Please feel free to reopen whenever you need.
