### ISSUE TITLE
Question about comments in the train.py

### ISSUE THREAD

**Issue by ChenyangLEI** [nttcslab/byol-a#12]
https://github.com/nttcslab/byol-a/blob/master/train.py

At line 67, there is comments for the shape of input. 
```
        # in fact, it should be (B, 1, F, T), e.g. (256, 1, 64, 96) where 64 is the number of mel bins
        paired_inputs = torch.cat(paired_inputs) # [(B,1,T,F), (B,1,T,F)] -> (2*B,1,T,F)
```

![image](https://user-images.githubusercontent.com/19903206/141122231-72bf6aaf-5940-40c4-a5fc-129286a8bf32.png)

However, it is different from the descriptions in config.yml file
```
# Shape of loh-mel spectrogram [F, T].
shape: [64, 96]
```

**Comment by Sreyan88** [comment]
Hi @ChenyangLEI,

I have a similar question, the norm in the acoustic world is to use [T,F], however, BYOL-A uses [F,T]. Any specific reason?

**Comment by daisukelab** [comment]
Hi @ChenyangLEI,
Thank you for sharing the issue, It's my fault.
As you might know, the comment in train.py is wrong. config.yaml is correct.

Hi @Sreyan88,
I didn't aware that the [F, T] order is against the convention.
It's basically following the output feature shape of the byol_a.dataset.MelSpectrogramLibrosa.
Thanks for sharing this issue with me.
I'd like to switch to it in the future. :)
