### ISSUE TITLE
A mistake in RunningMean

### ISSUE THREAD

**Issue by WhiteTeaDragon** [nttcslab/byol-a#13]
Thank you for the fascinating paper and the code to reproduce it!

I think there might be a problem in RunningMean. The current formula (the same in v1 and v2) looks like this: 

$$ m_n = m_{n - 1} + \frac{a_n - m_{n - 1}}{n - 1}, $$

which is inconsistent with the correct formula listed on StackOverflow:

$$ m_n = m_{n - 1} + \frac{a_n - m_{n - 1}}{n}. $$

The problem is that self.n is incremented after the new mean is computed. Could you please either correct me if I am wrong or correct the code?

**Comment by WhiteTeaDragon** [comment]
Thank you for your answer! The fix seems correct.

**Comment by daisukelab** [comment]
Hi @WhiteTeaDragon,

Just FYI, the issue has been fixed in the repository with exactly the same change above.
I have tested by pre-training on FSD50K and evaluating the pre-trained model to make it very sure.

Please let me know if you notice any further issues. Thanks!

**Comment by WhiteTeaDragon** [comment]
Thank you very much for your fix!
